In [1]:
import pandas as pd
bollywood = pd.read_csv('archive/bollywood.csv',encoding='latin-1')

In [2]:
bollywood.head()

,Year,Title,Director,Cast,Genre,Release Month,Release Date,Highest Grosser By Year(in crores)
0,1920,Balika Badhu a.k.a. Baby Bride,P. T. Shaida (Tulsidutt Shaida),"shaida,pandit,ali,miss,tarak,bagcha,tulsidutt",social,NaN,NaN,NaN
1,1920,Daksha Yagna a.k.a. Sati Parvati,Vishnupant Divekar,"prabha,khalil,vaidya",mythology,NaN,NaN,NaN
2,1920,Jalandhar Vrinda a.k.a. Sati Tulsi Vrinda,G. V. Sane,unknown,mythology,NaN,NaN,NaN
3,1920,Kansa Vadha a.k.a. End Of The Tyrant King,G. V. Sane,unknown,mythology,NaN,NaN,NaN
4,1920,Katorabhar Khoon a.k.a.The Stinger Stung a.k.a...,S. N. Patankar,"koregaonkar,gokhale,vyas,trymbakrao,pradhan,ta...",social,NaN,NaN,NaN

In [3]:
print(bollywood.shape)
bollywood.info

(9682, 8)

<bound method DataFrame.info of       Year                                              Title  \
0     1920                     Balika Badhu a.k.a. Baby Bride
1     1920                   Daksha Yagna a.k.a. Sati Parvati
2     1920          Jalandhar Vrinda a.k.a. Sati Tulsi Vrinda
3     1920          Kansa Vadha a.k.a. End Of The Tyrant King
4     1920  Katorabhar Khoon a.k.a.The Stinger Stung a.k.a...
...    ...                                                ...
9677  2019                                            Panipat
9678  2019                                Pati, Patni Aur Woh
9679  2019                                         Mardaani 2
9680  2019                                          Dabangg 3
9681  2019                                          Good News

                             Director  \
0     P. T. Shaida (Tulsidutt Shaida)
1                  Vishnupant Divekar
2                          G. V. Sane
3                          G. V. Sane
4                      S. N. Patankar
...                               ...
9677               Ashutosh Gowariker
9678                    Mudassar Aziz
9679                     Gopi Puthran
9680                      Prabhu Deva
9681                        Raj Mehta

                                                   Cast           Genre  \
0         shaida,pandit,ali,miss,tarak,bagcha,tulsidutt          social
1                                  prabha,khalil,vaidya       mythology
2                                               unknown       mythology
3                                               unknown       mythology
4     koregaonkar,gokhale,vyas,trymbakrao,pradhan,ta...          social
...                                                 ...             ...
9677       Sanjay DuttArjun KapoorKriti SanonKabir Bedi   Action/battle
9678           Kartik AaryanBhumi PednekarAnanya Panday          Comedy
9679  Rani MukherjeeVikram Singh ChauhanShruti Bapna...  Crime Thriller
9680  Salman KhanSonakshi SinhaArbaaz KhanMahie Gill...          Action
9681  Akshay KumarKareena KapoorDiljit DosanjhKiara ...          Comedy

     Release Month  Release Date  Highest Grosser By Year(in crores)
0              NaN           NaN                                 NaN
1              NaN           NaN                                 NaN
2              NaN           NaN                                 NaN
3              NaN           NaN                                 NaN
4              NaN           NaN                                 NaN
...            ...           ...                                 ...
9677           DEC           6.0                                 NaN
9678           DEC           6.0                                 NaN
9679           DEC          13.0                                 NaN
9680           DEC          20.0                                 NaN
9681           DEC          27.0                                 NaN

[9682 rows x 8 columns]>

In [4]:
bollywood.tail(5)

,Year,Title,Director,Cast,Genre,Release Month,Release Date,Highest Grosser By Year(in crores)
9677,2019,Panipat,Ashutosh Gowariker,Sanjay DuttArjun KapoorKriti SanonKabir Bedi,Action/battle,DEC,6.0,NaN
9678,2019,"Pati, Patni Aur Woh",Mudassar Aziz,Kartik AaryanBhumi PednekarAnanya Panday,Comedy,DEC,6.0,NaN
9679,2019,Mardaani 2,Gopi Puthran,Rani MukherjeeVikram Singh ChauhanShruti Bapna...,Crime Thriller,DEC,13.0,NaN
9680,2019,Dabangg 3,Prabhu Deva,Salman KhanSonakshi SinhaArbaaz KhanMahie Gill...,Action,DEC,20.0,NaN
9681,2019,Good News,Raj Mehta,Akshay KumarKareena KapoorDiljit DosanjhKiara ...,Comedy,DEC,27.0,NaN

In [5]:
bollywood.sample(3)

,Year,Title,Director,Cast,Genre,Release Month,Release Date,Highest Grosser By Year(in crores)
5046,1975,Chaitali,Hrishikesh Mukherjee,"banu,dharmendra,saira",unknown,NaN,NaN,NaN
4562,1969,Ittefaq,Yash Chopra,"nanda,sujit,jagirdar,rajesh,khanna,kumar,gajan...",unknown,NaN,NaN,NaN
8535,2009,Paa,R. Balki,"balan,abhishek,bachchan,paresh,vidya,amitabh,r...","family,drama",DEC,4.0,NaN

In [6]:
bollywood.loc[10:20,["Title","Director","Genre"]]

,Title,Director,Genre
10,Narsinh Mehta,"Suchet Singh, Shukle",devotional
11,Ram Janma,G. V. Sane,mythology
12,Rama Or Maya,"Suchet Singh, Shukle",mythology
13,Sairandhri,Baburao Painter,mythology
14,Shakuntala,Suchet Singh,mythology
15,Shakuntala,Shree Nath Patankar,"mythology,drama"
16,Shri Krishna Leela,G. V. Sane,mythology
17,Shri Rama Janma,G. V. Sane,mythology
18,Sita Swayamwar a.k.a. Sita's Marriage,Shree Nath Patankar,mythology
19,The Enchanted Pills a.k.a. Vichitra Gutika,S. N. Patankar,social
20,Vikram Urvashi,Kanjibhai Rathod,mythology

In [7]:
bollywood.iloc[0:5,0:3]

,Year,Title,Director
0,1920,Balika Badhu a.k.a. Baby Bride,P. T. Shaida (Tulsidutt Shaida)
1,1920,Daksha Yagna a.k.a. Sati Parvati,Vishnupant Divekar
2,1920,Jalandhar Vrinda a.k.a. Sati Tulsi Vrinda,G. V. Sane
3,1920,Kansa Vadha a.k.a. End Of The Tyrant King,G. V. Sane
4,1920,Katorabhar Khoon a.k.a.The Stinger Stung a.k.a...,S. N. Patankar

In [8]:
bollywood.sort_values(["Year"],ascending=False)

,Year,Title,Director,Cast,Genre,Release Month,Release Date,Highest Grosser By Year(in crores)
9657,2019,Pal Pal Dil Ke Paas,Sunny Deol,Karan DeolSahher Bambba,Drama/Romance,SEP,20.0,NaN
9650,2019,Batla House,Nikhil Advani,John AbrahamMrunal Thakur,Action,AUG,15.0,NaN
9665,2019,Laal Kaptaan,Navdeep Singh,Saif Ali Khan,Action,OCT,18.0,NaN
9681,2019,Good News,Raj Mehta,Akshay KumarKareena KapoorDiljit DosanjhKiara ...,Comedy,DEC,27.0,NaN
9664,2019,Ghost,Vikram Bhatt,Sanaya Irani,Horror Thriller,OCT,18.0,NaN
...,...,...,...,...,...,...,...,...
11,1920,Ram Janma,G. V. Sane,unknown,mythology,NaN,NaN,NaN
10,1920,Narsinh Mehta,"Suchet Singh, Shukle","kanjibhai,rathod",devotional,NaN,NaN,NaN
9,1920,Narasinha Avtar,Shree Nath Patankar,unknown,mythology,NaN,NaN,NaN
15,1920,Shakuntala,Shree Nath Patankar,unknown,"mythology,drama",NaN,NaN,NaN
0,1920,Balika Badhu a.k.a. Baby Bride,P. T. Shaida (Tulsidutt Shaida),"shaida,pandit,ali,miss,tarak,bagcha,tulsidutt",social,NaN,NaN,NaN

In [9]:
bollywood.sort_values(["Release Month","Year"],ascending=False)

,Year,Title,Director,Cast,Genre,Release Month,Release Date,Highest Grosser By Year(in crores)
9653,2019,Chhichhore,Nitesh Tiwari,Sushant Singh RajputShraddha KapoorVarun Sharm...,Comedy-Drama,SEP,6.0,NaN
9654,2019,Dream Girl,Raaj Shaandilyaa,Ayushmann KhurranaNushrat Bharucha,Comedy,SEP,13.0,NaN
9655,2019,Section 375,Ajay Bahl,Akshaye KhannaRicha ChadhaRahul BhatMeera Chopra,crime thriller,SEP,13.0,NaN
9656,2019,The Zoya Factor,Abhishek Sharma,Sonam KapoorDulquer SalmaanSanjay Kapoor,Drama,SEP,20.0,NaN
9657,2019,Pal Pal Dil Ke Paas,Sunny Deol,Karan DeolSahher Bambba,Drama/Romance,SEP,20.0,NaN
...,...,...,...,...,...,...,...,...
16,1920,Shri Krishna Leela,G. V. Sane,unknown,mythology,NaN,NaN,NaN
17,1920,Shri Rama Janma,G. V. Sane,unknown,mythology,NaN,NaN,NaN
18,1920,Sita Swayamwar a.k.a. Sita's Marriage,Shree Nath Patankar,limaye,mythology,NaN,NaN,NaN
19,1920,The Enchanted Pills a.k.a. Vichitra Gutika,S. N. Patankar,"damuanna,dighe,marathe,joshi,gokhale,trymbakra...",social,NaN,NaN,NaN
20,1920,Vikram Urvashi,Kanjibhai Rathod,"n,lina,r,vaidya,valentine",mythology,NaN,NaN,NaN

In [10]:
bollywood.query('Year>2000')

,Year,Title,Director,Cast,Genre,Release Month,Release Date,Highest Grosser By Year(in crores)
7590,2001,Abhay,Suresh Krishna,"tandon,koirala,manisha,hassan,raveena,kamal",thriller,NaN,NaN,NaN
7591,2001,Aamdani Atthani Kharcha Rupaiyaa,K. Raghavendra Rao,"tabu,juhi,lever,chawla,koppikar,isha,johnny,go...","family,drama",NaN,NaN,NaN
7592,2001,Aashiq,Indra Kumar,"kapoor,bobby,karisma,deol","action,comedy",NaN,NaN,NaN
7593,2001,Afsana Dilwalon Ka,J. Om Prakash,"kaul,ashish,rahul,juni,roy",romance,NaN,NaN,NaN
7594,2001,Ajnabee,Abbas Mustan,"kapoor,bobby,bipasha,kumar,deol,akshay,basu,ka...","crime,suspense,thriller",NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
9677,2019,Panipat,Ashutosh Gowariker,Sanjay DuttArjun KapoorKriti SanonKabir Bedi,Action/battle,DEC,6.0,NaN
9678,2019,"Pati, Patni Aur Woh",Mudassar Aziz,Kartik AaryanBhumi PednekarAnanya Panday,Comedy,DEC,6.0,NaN
9679,2019,Mardaani 2,Gopi Puthran,Rani MukherjeeVikram Singh ChauhanShruti Bapna...,Crime Thriller,DEC,13.0,NaN
9680,2019,Dabangg 3,Prabhu Deva,Salman KhanSonakshi SinhaArbaaz KhanMahie Gill...,Action,DEC,20.0,NaN
9681,2019,Good News,Raj Mehta,Akshay KumarKareena KapoorDiljit DosanjhKiara ...,Comedy,DEC,27.0,NaN

In [11]:
bollywood.query('Genre=="action" and Year>2010')

,Year,Title,Director,Cast,Genre,Release Month,Release Date,Highest Grosser By Year(in crores)
8721,2011,Singham,Rohit Shetty,"prakash,raj,ajay,devgn,kajal,aggarwal",action,JUL,15.0,NaN
8735,2011,Shabri,Lalit Marathe,"koppikar,isha",action,AUG,26.0,NaN
8800,2012,Tezz,Priyadarshan,"kapoor,khan,27,boman,ranaut,zayed,mohanlal,aja...",action,APR,27.0,NaN
8879,2013,Mumbai Mirror,Ankush Bhatt,"khan,joshi,prakash,raj,sachiin,gihana",action,JAN,18.0,NaN
8885,2013,Vishwaroop,Kamal Haasan,"haasan,jeremiah,rahul,andrea,kumar,kapur,pooja...",action,FEB,1.0,NaN
8893,2013,Zilla Ghaziabad,Anand Kumar,"lamba,paresh,dutt,warsi,sanjay,oberoi,vivek,ra...",action,FEB,22.0,NaN
8901,2013,Rangrezz,Priyadarshan,"evelyn,yadav,anand,jackky,sharma,rajpal,bhagna...",action,MAR,20.0,NaN
8925,2013,Enemmy,Ashu Trikha,"chakraborty,mahakshay,lever,chaudhary,menon,ka...",action,JUN,21.0,NaN
8929,2013,Policegiri,K. S. Ravikumar,"prakash,puri,prachi,dutt,sanjay,73,raj,desai,om",action,JUL,5.0,NaN
8978,2013,Singh Saab The Great,Anil Sharma,"urvashi,sunny,johny,lever,rao,amrita,123,raute...",action,NOV,22.0,NaN
8983,2013,Dhoom 3,Vijay Krishna Acharya,"khan,abhishek,bachchan,katrina,uday,kaif,chopr...",action,DEC,20.0,589.2
8999,2014,Gunday,Ali Abbas Zafar,"kapoor,priyanka,khan,arjun,ranveer,chopra,irrf...",action,FEB,14.0,NaN
9020,2014,Dishkiyaoon,Sanamjit Talwar,"ayesha,sunny,baweja,harman,khanna,deol,narayan...",action,MAR,28.0,NaN
9037,2014,Angry Young Man,Ramesh Rout,"sinha,rathod,ajay,sinh,prachi",action,MAY,2.0,NaN
9041,2014,Koyelaanchal,Ashu Trikha,"vinod,suniel,vipino,khanna,shetty",action,MAY,9.0,NaN
9049,2014,Kochadaiiyaan,Soundarya Rajnikanth,"deepika,shroff,jackie,rajinikanth,padukone,sho...",action,MAY,23.0,NaN
9068,2014,Singham Returns,Rohit Shetty,"kapoor,anupam,amol,ajay,kher,devgn,gupte,kareena",action,AUG,15.0,NaN
9085,2014,Bang Bang!,Siddharth Anand,"hrithik,javed,roshan,katrina,kaif,jaffrey",action,OCT,2.0,NaN
9186,2015,Baahubali,S. S. Rajamouli,"prabhas,tamannaah,anushka,daggubati,rana,bhati...",action,JUL,10.0,NaN
9228,2015,Ranbanka,Aryeman Ramsay,"manish,paul,thakur,ravi,pooja,kishan",action,NOV,6.0,NaN
9266,2016,Rocky Handsome,Nishikant Kamat,"haasan,shruti,abraham,john,kaur,nathalia",action,MAR,25.0,NaN
9272,2016,Laal Rang,Syed Ahmad Afzal,"randeep,bajpai,rajneesh,oberoi,piaa,duggal,aks...",action,APR,22.0,NaN
9274,2016,Baaghi,Sabbir Khan,"kapoor,shroff,babu,grover,sunil,tiger,sudheer,...",action,APR,29.0,NaN
9281,2016,Khel Toh Ab Shuru Hoga,Kunal V Singh,"devshi,ruslaan,khanduri,mumtaz",action,MAY,13.0,NaN
9286,2016,Veerappan,Ram Gopal Varma,"khan,bharadwaj,lisa,joshi,ray,jadhav,usha,sand...",action,MAY,27.0,NaN
9308,2016,Kabali,Pa. Ranjith,"apte,rajinikanth,winston,radhika,chao",action,JUL,29.0,NaN
9309,2016,Dishoom,Rohit Dhawan,"kapoor,jacqueline,saqib,varun,dhawan,fernandez...",action,JUL,29.0,NaN
9317,2016,Waarrior Savitri,Param Gill,"pinder,lucy,raizada,rajat,niharica,barmecha",action,AUG,25.0,NaN
9351,2016,Force 2,Abhinay Deo,"bhasin,sinha,sonakshi,raj,abraham,john,tahir",action,NOV,18.0,NaN
9367,2017,The Ghazi Attack,Sankalp Reddy,"pannu,daggubati,rana,menon,kay,taapsee,kulkarn...",action,FEB,17.0,NaN
9373,2017,Commando 2,Deven Bhojani,"esha,gupta,sharma,vidyut,jammwal,adah",action,MAR,3.0,NaN
9433,2017,Babumoshai Bandookbaaz,Kushan Nandy,"shivhare,nawazuddin,bidita,murali,sachin,chaub...",action,AUG,25.0,NaN
9452,2017,Mein Terrorist Nahi Hoon,Arjin Uppal,"dev,maembong,jalal,farida,rahul,grover,afiq,ch...",action,OCT,6.0,NaN

In [12]:
bollywood.loc[bollywood["Director"].str.contains("chopra",case=False)]

,Year,Title,Director,Cast,Genre,Release Month,Release Date,Highest Grosser By Year(in crores)
2764,1949,Karwat,"Prakash, B.R. Chopra (uncredited)","vasantrao,anwaribai,ratanpriya,deepak,baburao,...",action,NaN,NaN,NaN
2917,1951,Afsana,B. R. Chopra,"veena,kumar,pran,jeevan,ashok","crime,romance,thriller",NaN,NaN,NaN
3178,1953,Shole,B. R. Chopra,"musharaf,master,rai,naaz,bina,kumar,krishna,ro...","social,family,drama",NaN,NaN,NaN
3207,1954,Chandni Chowk,B. R. Chopra,"meena,kumari,smriti,achala,sachdev,katju,yasho...",unknown,NaN,NaN,NaN
3447,1956,Ek Hi Rasta,B. R. Chopra,"meena,kumari,kumkum,daisy,yashodra,kumar,brahm...","social,drama",NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
9015,2014,W,Tarun Madan Chopra,"sonal,danish,giani,pandor,leslie,meer,abhey,al...",thriller,MAR,14.0,NaN
9356,2016,Befikre,Aditya Chopra,"kapoor,singh,ranveer,vaani",romance,DEC,9.0,NaN
9458,2017,Ittefaq,Abhay Chopra,"sinha,sonakshi,sidharth,khanna,malhotra,akshaye",thriller,NOV,3.0,NaN
9607,2019,Ek Ladki Ko Dekha Toh Aisa Laga,Shelly Chopra Dhar,Anil KapoorSonam KapoorJuhi ChawlaRajkummar Rao,Romance,FEB,1.0,NaN
9672,2019,Shikara - A Love Letter from Kashmir,Vidhu Vinod Chopra,TBA,Historical/Romance,NOV,8.0,NaN

In [13]:
def get_era(Year):
    if Year<1980:
        return "Classic"
    elif Year<2010:
        return "Modern"
    else:
        return "Contemporary"
bollywood["Era"] = bollywood["Year"].apply(get_era)
bollywood[["Year","Title","Era"]].head()

   Year                                              Title      Era
0  1920                     Balika Badhu a.k.a. Baby Bride  Classic
1  1920                   Daksha Yagna a.k.a. Sati Parvati  Classic
2  1920          Jalandhar Vrinda a.k.a. Sati Tulsi Vrinda  Classic
3  1920          Kansa Vadha a.k.a. End Of The Tyrant King  Classic
4  1920  Katorabhar Khoon a.k.a.The Stinger Stung a.k.a...  Classic

In [14]:
#bollywood.drop(columns="Cast",inplace=True)
bollywood.rename(columns={"Release Month":"month"},inplace=True)

In [15]:
#Find all drama movies released in December after 1990, sorted by Year newest first. 
# Show only Title, Year, Director.
bollywood[(bollywood["month"] == "DEC") & (bollywood["Year"] > 1990) & (bollywood["Genre"] == "drama")][["Title", "Year", "Director"]].sort_values("Year", ascending=False)

                          Title  Year              Director
9234                    Kajarya  2015      Madhureeta Anand
9115               Take It Easy  2014       Sunil Prem Vyas
9112  Bhopal: A Prayer for Rain  2014            Ravi Kumar
9113        Mumbai Delhi Mumbai  2014        Satish Rajwade
9118          LUV...Phir Kabhie  2014            Ajay Yadav
8982              What the Fish  2013         Gurmmet Singh
8764          The Dirty Picture  2011         Milan Luthria
8662              Isi Life Mein  2010        Vidhi Kasliwal
8660                      Mirch  2010          Vinay Shukla
8665       Ada... A Way of Life  2010          Tanvir Ahmad
8537       Raat Gayi Baat Gayi?  2009        Saurabh Shukla
8437           Meerabai Not Out  2008  Chandrakant Kulkarni

In [16]:
#Get the shape, column names, and first 3 rows of the dataframe. (3 separate lines)
bollywood.shape

(9682, 9)

In [17]:
bollywood.head(3)

,Year,Title,Director,Cast,Genre,month,Release Date,Highest Grosser By Year(in crores),Era
0,1920,Balika Badhu a.k.a. Baby Bride,P. T. Shaida (Tulsidutt Shaida),"shaida,pandit,ali,miss,tarak,bagcha,tulsidutt",social,NaN,NaN,NaN,Classic
1,1920,Daksha Yagna a.k.a. Sati Parvati,Vishnupant Divekar,"prabha,khalil,vaidya",mythology,NaN,NaN,NaN,Classic
2,1920,Jalandhar Vrinda a.k.a. Sati Tulsi Vrinda,G. V. Sane,unknown,mythology,NaN,NaN,NaN,Classic

In [18]:
bollywood.columns.tolist()

['Year',
 'Title',
 'Director',
 'Cast',
 'Genre',
 'month',
 'Release Date',
 'Highest Grosser By Year(in crores)',
 'Era']

In [19]:
#Sort the dataframe by Title alphabetically (A to Z).
bollywood.sort_values("Title").head()

,Year,Title,Director,Cast,Genre,month,Release Date,Highest Grosser By Year(in crores),Era
3266,1954,"""Prisoner Of Golconda"" a.k.a. ""Golconda ka Qaidi""",Premnath,"shobhana,ermeline,rajendranath,premnath,rai,sa...",costume,NaN,NaN,NaN,Classic
471,1927,''Sati Savitri a.k.a. Savitri Satyavan a.k.a. ...,Pandurang Talegiri,"gade,baburao,kulkarni,pandurang,varne,gangubai...",mythology,NaN,NaN,NaN,Classic
6653,1991,100 Days,Parto Ghosh,"madhuri,shroff,jackie,dixit",thriller,NaN,NaN,NaN,Modern
9518,2018,102 Not Out,Umesh Shukla,Amitabh BachchanRishi Kapoor,Comedy,MAY,4.0,NaN,Contemporary
6247,1987,108 Teerthyatra,Rajpati,"bhatt,anand,pravin,nayan,jeetu","fantasy,drama,comedy",NaN,NaN,NaN,Modern

In [20]:
#Select only the Title and Year columns and store it in a new variable called df_small.
bollywood_small = bollywood[["Title","Year"]]

In [21]:
bollywood_small

                                                  Title  Year
0                        Balika Badhu a.k.a. Baby Bride  1920
1                      Daksha Yagna a.k.a. Sati Parvati  1920
2             Jalandhar Vrinda a.k.a. Sati Tulsi Vrinda  1920
3             Kansa Vadha a.k.a. End Of The Tyrant King  1920
4     Katorabhar Khoon a.k.a.The Stinger Stung a.k.a...  1920
...                                                 ...   ...
9677                                            Panipat  2019
9678                                Pati, Patni Aur Woh  2019
9679                                         Mardaani 2  2019
9680                                          Dabangg 3  2019
9681                                          Good News  2019

[9682 rows x 2 columns]

In [22]:
#Filter movies from the year 1990 exactly. How many were released that year?
bollywood.query('Year>1990').head()

,Year,Title,Director,Cast,Genre,month,Release Date,Highest Grosser By Year(in crores),Era
6653,1991,100 Days,Parto Ghosh,"madhuri,shroff,jackie,dixit",thriller,NaN,NaN,NaN,Modern
6654,1991,Aag Laga Do Sawan Ko,Anup Malik,"harish,patel",unknown,NaN,NaN,NaN,Modern
6655,1991,Aaj Ka Samson,Kuku Kapoor,"chaddha,kapoor,sahila,goga,hemant,birje","action,romance",NaN,NaN,NaN,Modern
6656,1991,Aakhri Cheekh,Kiran Ramsay,"ghatge,dhawan,vijay,anil,arora,vijayendra",horror,NaN,NaN,NaN,Modern
6657,1991,Afsana Pyar Ka,Shahjahan,"khan,aamir,kothari,neelam",romance,NaN,NaN,NaN,Modern

In [23]:
#Use .iloc to get the movie at row index 99 (the 100th row).
bollywood.iloc[100]

Year                                                                               1922
Title                                 Ratnavali a.k.a. Ratnabali a.k.a. Sea Nymph Of...
Director                                                  Jyotish Bannerjee, C. Legrand
Cast                                  gohar,c,pandit,patience,miss,albertina,cooper,...
Genre                                                                  mythology,legend
month                                                                               NaN
Release Date                                                                        NaN
Highest Grosser By Year(in crores)                                                  NaN
Era                                                                             Classic
Name: 100, dtype: object

In [24]:
#Filter movies from EITHER "action" OR "comedy" genre.
bollywood.query('Genre=="action" or Genre=="comedy"')

,Year,Title,Director,Cast,Genre,month,Release Date,Highest Grosser By Year(in crores),Era
85,1922,Lady Teacher,Dhirendranath Ganguly,unknown,comedy,NaN,NaN,NaN,Classic
101,1922,Sadhu Aur Shaitan,"Nitish Lahiri, Dhirendranath Ganguly","dhirendranath,sushilabala,lina,ganguly,manmath...",comedy,NaN,NaN,NaN,Classic
406,1927,At The Clang Of Fetters a.k.a. Janjir Ne Jhank...,Harshadrai Mehta,"joshi,haidershah,nandram,gulab,gangaram,alam,s...",action,NaN,NaN,NaN,Classic
412,1927,Bhedi Trishul a.k.a. Hidden Treasure,Nanubhai B. Desai,"kapoor,lobo,master,a,vithal,miss,janibabu,p,pr...",action,NaN,NaN,NaN,Classic
548,1928,Kelor Kirti,Sudhansu Mustafi,"niharbala,bela,rani,lalu,bose",comedy,NaN,NaN,NaN,Classic
...,...,...,...,...,...,...,...,...,...
9450,2017,Chef,Raja Krishna Menon,"khan,karthik,dhanish,ali,saif,padmapriya,janak...",comedy,OCT,6.0,NaN,Contemporary
9452,2017,Mein Terrorist Nahi Hoon,Arjin Uppal,"dev,maembong,jalal,farida,rahul,grover,afiq,ch...",action,OCT,6.0,NaN,Contemporary
9455,2017,Golmaal Again,Rohit Shetty,"prakash,tusshar,talpade,kapoor,tabu,neil,and,c...",comedy,OCT,20.0,NaN,Contemporary
9473,2017,Firangi,Rajiv Dhingra,"sonnenblick,sharma,kapil,edward,badola,varun",comedy,DEC,1.0,NaN,Contemporary
9474,2017,Fukrey Returns,Mrighdeep Singh Lamba,"anand,pulkit,samrat,sharma,varun,priya",comedy,DEC,8.0,NaN,Contemporary

In [25]:
#Get the unique genres in the dataset. How many distinct genres are there?
bollywood["Genre"].unique()

<ArrowStringArray>
[            'social',          'mythology',            'unknown',
         'devotional',    'mythology,drama',        'documentary',
      'social,comedy',             'legend',       'social,drama',
         'historical',
 ...
       'Family Drama',   'Thriller, Comedy',       'Comedy-Drama',
     'crime thriller',   'Action, Thriller',     'Romantic drama',
 'Historical/Romance',       'Black Comedy',      'Action/battle',
     'Crime Thriller']
Length: 624, dtype: str

In [26]:
bollywood["Genre"].nunique()

623

In [27]:
#Use .loc to get rows where Year is between 1970 and 1980 (inclusive). 
# Do NOT use & conditions — use .loc's between shortcut.
bollywood.loc[bollywood["Year"].between(1970,1980)]

,Year,Title,Director,Cast,Genre,month,Release Date,Highest Grosser By Year(in crores),Era
4617,1970,Aag Aur Daag,A. Salaam,"puri,joy,mukherjee,madan",action,NaN,NaN,NaN,Classic
4618,1970,Aan Milo Sajna,Mukul Dutt,"vinod,asha,parekh,rajesh,khanna",drama,NaN,NaN,NaN,Classic
4619,1970,Aansoo Aur Muskan,P. Madhavan,"bindu,padmini",drama,NaN,NaN,NaN,Classic
4620,1970,Abhinetri,Subodh Mukherjee,"shashi,kapoor,malini,mukherjee,deb,hema",drama,NaN,NaN,NaN,Classic
4621,1970,Bachpan,Kotayya Pratyagatma,"sanjeev,kumar,tanuja",drama,NaN,NaN,NaN,Classic
...,...,...,...,...,...,...,...,...,...
5534,1980,Unees-Bees,Swaroop Kumar,"chakraborty,yogeeta,rita,bhaduri,bali,mithun",unknown,NaN,NaN,NaN,Modern
5535,1980,Yari Dushmani,Sikandar Khanna,"khan,amjad,dutt,reena,sunil,roy",unknown,NaN,NaN,NaN,Modern
5536,1980,Yeh Kaisa Insaf?,Narayana Rao Dasari,"vinod,mehra,shabana,sarika,azmi",drama,NaN,NaN,NaN,Modern
5537,1980,Zakhmon Ke Nishan,Diljeet Bassi,"arora,vinod,vijay,mehra",unknown,NaN,NaN,NaN,Modern
5538,1980,Zalim,B. Subhash,"chandavarkar,vinod,leena,khanna,pran,roy,nirupa",unknown,NaN,NaN,NaN,Modern

In [28]:
#Sort by Year descending, but if two movies share the same year, sort those by Title A→Z.
bollywood.sort_values(["Year","Title"],ascending=[False,True])

,Year,Title,Director,Cast,Genre,month,Release Date,Highest Grosser By Year(in crores),Era
9601,2019,72 Hours: Martyr Who Never Died,Avinash Dhyani,Avinash DhyaniMukesh TiwariVirendra SaxenaAlka...,Biographical Drama,JAN,18.0,NaN,Contemporary
9625,2019,Albert Pinto Ko Gussa Kyun Aata Hai?,Soumitra Ranade,Manav KaulNandita DasSaurabh ShuklaKishor Kadam,Thriller,APR,12.0,NaN,Contemporary
9609,2019,Amavas,Bhushan Patel,Sachiin JoshiVivan BhatenaNargis Fakhri,Horror/Thriller,FEB,8.0,NaN,Contemporary
9645,2019,Arjun Patiala,Rohit Jugraj,Diljit DosanjhKriti SanonVarun SharmaRonit Roy,Romantic Comedy,JUL,26.0,NaN,Contemporary
9637,2019,Article 15,Anubhav Sinha,Ayushmann KhurranaIsha TalwarNassarManoj Pahwa...,Drama/ Thriller,JUN,28.0,NaN,Contemporary
...,...,...,...,...,...,...,...,...,...
16,1920,Shri Krishna Leela,G. V. Sane,unknown,mythology,NaN,NaN,NaN,Classic
17,1920,Shri Rama Janma,G. V. Sane,unknown,mythology,NaN,NaN,NaN,Classic
18,1920,Sita Swayamwar a.k.a. Sita's Marriage,Shree Nath Patankar,limaye,mythology,NaN,NaN,NaN,Classic
19,1920,The Enchanted Pills a.k.a. Vichitra Gutika,S. N. Patankar,"damuanna,dighe,marathe,joshi,gokhale,trymbakra...",social,NaN,NaN,NaN,Classic
20,1920,Vikram Urvashi,Kanjibhai Rathod,"n,lina,r,vaidya,valentine",mythology,NaN,NaN,NaN,Classic

In [29]:
#Reset the index after filtering. Filter movies after year 2000,
#  then reset the index so it starts from 0 again.
bollywood.loc[bollywood["Year"]>2000].reset_index(drop=True)

,Year,Title,Director,Cast,Genre,month,Release Date,Highest Grosser By Year(in crores),Era
0,2001,Abhay,Suresh Krishna,"tandon,koirala,manisha,hassan,raveena,kamal",thriller,NaN,NaN,NaN,Modern
1,2001,Aamdani Atthani Kharcha Rupaiyaa,K. Raghavendra Rao,"tabu,juhi,lever,chawla,koppikar,isha,johnny,go...","family,drama",NaN,NaN,NaN,Modern
2,2001,Aashiq,Indra Kumar,"kapoor,bobby,karisma,deol","action,comedy",NaN,NaN,NaN,Modern
3,2001,Afsana Dilwalon Ka,J. Om Prakash,"kaul,ashish,rahul,juni,roy",romance,NaN,NaN,NaN,Modern
4,2001,Ajnabee,Abbas Mustan,"kapoor,bobby,bipasha,kumar,deol,akshay,basu,ka...","crime,suspense,thriller",NaN,NaN,NaN,Modern
...,...,...,...,...,...,...,...,...,...
2087,2019,Panipat,Ashutosh Gowariker,Sanjay DuttArjun KapoorKriti SanonKabir Bedi,Action/battle,DEC,6.0,NaN,Contemporary
2088,2019,"Pati, Patni Aur Woh",Mudassar Aziz,Kartik AaryanBhumi PednekarAnanya Panday,Comedy,DEC,6.0,NaN,Contemporary
2089,2019,Mardaani 2,Gopi Puthran,Rani MukherjeeVikram Singh ChauhanShruti Bapna...,Crime Thriller,DEC,13.0,NaN,Contemporary
2090,2019,Dabangg 3,Prabhu Deva,Salman KhanSonakshi SinhaArbaaz KhanMahie Gill...,Action,DEC,20.0,NaN,Contemporary
2091,2019,Good News,Raj Mehta,Akshay KumarKareena KapoorDiljit DosanjhKiara ...,Comedy,DEC,27.0,NaN,Contemporary

In [30]:
#Add a column "decade" that shows which decade each movie is from — 
# e.g. 1950s, 1960s, 1970s…

bollywood["Decade"] = (bollywood["Year"] // 10*10).astype(str)+"s"
bollywood["Decade"].head()

0    1920s
1    1920s
2    1920s
3    1920s
4    1920s
Name: Decade, dtype: str

In [31]:
bollywood.loc[bollywood.Year.between(1990,2000)]

,Year,Title,Director,Cast,Genre,month,Release Date,Highest Grosser By Year(in crores),Era,Decade
6553,1990,"Aadhi Haqeeqat, Aadha Fasana",Dilip Ghosh,unknown,unknown,NaN,NaN,NaN,Modern,1990s
6554,1990,Aadmi Aur Apsara,"J. Om Prakash, K. Raghavendra Rao","amrish,sridevi,puri,chiranjeevi",unknown,NaN,NaN,NaN,Modern,1990s
6555,1990,Aaj Ka Arjun,K.C. Bokadia,"bachchan,jayapradha,amitabh","action,drama",NaN,NaN,NaN,Modern,1990s
6556,1990,Aag Ka Daag Ka Dariya,S.V. Rajendra Singh,"padmini,rekha,kolhapure,kumar,dilip,amrita,singh",drama,NaN,NaN,NaN,Modern,1990s
6557,1990,Aag Ka Gola,David Dhawan,"sunny,dimple,puran,kapadia,deol,archana,singh",action,NaN,NaN,NaN,Modern,1990s
...,...,...,...,...,...,...,...,...,...,...
7585,2000,Tarkieb,Esmayeel Shroff,"soman,tabu,patekar,shilpa,nana,milind,shetty","suspense,thriller",NaN,NaN,NaN,Modern,2000s
7586,2000,Tera Jadoo Chal Gayaa,A. Muthu,"abhishek,bachchan,suri,reddy,sanjay,kirti",romance,NaN,NaN,NaN,Modern,2000s
7587,2000,Tere Liye,Sanjay Gadhvi,"sonali,khan,imran,paintal,hiten,kohli,ahmed,ne...",unknown,NaN,NaN,NaN,Modern,2000s
7588,2000,Tune Mera Dil Le Liyaa,B.B. Bhalla,"kapoor,tandon,shah,rahul,naseeruddin,shakti,ra...",unknown,NaN,NaN,NaN,Modern,2000s
7589,2000,Zindagi Zindabad,Sumitra Bhave??Sunil Sukthankar,"vasisht,gunaji,mita,uttara,milind,bhadkamkar,a...",unknown,NaN,NaN,NaN,Modern,2000s

In [32]:
bollywood.sort_values(["Year","Title"],ascending=[False,True]).head(10)

,Year,Title,Director,Cast,Genre,month,Release Date,Highest Grosser By Year(in crores),Era,Decade
9601,2019,72 Hours: Martyr Who Never Died,Avinash Dhyani,Avinash DhyaniMukesh TiwariVirendra SaxenaAlka...,Biographical Drama,JAN,18.0,NaN,Contemporary,2010s
9625,2019,Albert Pinto Ko Gussa Kyun Aata Hai?,Soumitra Ranade,Manav KaulNandita DasSaurabh ShuklaKishor Kadam,Thriller,APR,12.0,NaN,Contemporary,2010s
9609,2019,Amavas,Bhushan Patel,Sachiin JoshiVivan BhatenaNargis Fakhri,Horror/Thriller,FEB,8.0,NaN,Contemporary,2010s
9645,2019,Arjun Patiala,Rohit Jugraj,Diljit DosanjhKriti SanonVarun SharmaRonit Roy,Romantic Comedy,JUL,26.0,NaN,Contemporary,2010s
9637,2019,Article 15,Anubhav Sinha,Ayushmann KhurranaIsha TalwarNassarManoj Pahwa...,Drama/ Thriller,JUN,28.0,NaN,Contemporary,2010s
9615,2019,Badla,Sujoy Ghosh,Amitabh BachchanTaapsee Pannu,Drama /Thriller,MAR,8.0,NaN,Contemporary,2010s
9673,2019,Bala,Amar Kaushik,Ayushmann KhurranaBhumi PednekarYami GautamSau...,Black Comedy,NOV,15.0,NaN,Contemporary,2010s
9650,2019,Batla House,Nikhil Advani,John AbrahamMrunal Thakur,Action,AUG,15.0,NaN,Contemporary,2010s
9596,2019,Battalion 609,Brijesh Batuknath Tripathi,Shoaib IbrahimElena KazanFarnaz ShettyVishwas ...,Action,JAN,11.0,NaN,Contemporary,2010s
9634,2019,Bharat,Ali Abbas Zafar,Salman KhanTabuKatrina KaifSunil GroverDisha P...,Drama,JUN,5.0,NaN,Contemporary,2010s

In [33]:
bollywood[bollywood["Director"].str.contains("Kumar",case=False)].count()

Year                                  302
Title                                 302
Director                              302
Cast                                  302
Genre                                 302
month                                  47
Release Date                           47
Highest Grosser By Year(in crores)      5
Era                                   302
Decade                                302
dtype: int64

In [34]:
import numpy as np
bollywood["old_or_new"] = np.where(bollywood["Year"]<1980,"old","new")
bollywood["old_or_new"]

0       old
1       old
2       old
3       old
4       old
       ...
9677    new
9678    new
9679    new
9680    new
9681    new
Name: old_or_new, Length: 9682, dtype: str

In [35]:
#Get all drama OR romance movies released after 1995. 
# Reset the index. Show the first 5 rows.
bollywood.query('Genre=="Drama" or Genre=="Romance"').where(bollywood["Year"]>1995).reset_index(drop=True).head()

,Year,Title,Director,Cast,Genre,month,Release Date,Highest Grosser By Year(in crores),Era,Decade,old_or_new
0,2018,Mukkabaaz,Anurag Kashyap,Vineet Kumar SinghZoya HussainRavi KishanJimmy...,Drama,JAN,12.0,NaN,Contemporary,2010s,new
1,2018,Union Leader,Sanjay Patel (filmmaker),Rahul BhatTillotama Shome,Drama,JAN,19.0,NaN,Contemporary,2010s,new
2,2018,Aiyaary,Neeraj Pandey,Sidharth MalhotraManoj BajpayeeRakul Preet Sin...,Drama,FEB,16.0,NaN,Contemporary,2010s,new
3,2018,Kuchh Bheege Alfaaz,Onir,Zain Khan DurraniGeetanjali Thapa,Romance,FEB,16.0,NaN,Contemporary,2010s,new
4,2018,Jaane Kyun De Yaaron,Akshay Anand,Raghu RajaAbhishek SharmaKabir BediChetna Pand...,Drama,FEB,16.0,NaN,Contemporary,2010s,new

In [36]:
result = bollywood.loc[50:100,["Title","Genre"]]
result.query('Genre=="Action"')

Empty DataFrame
Columns: [Title, Genre]
Index: []

In [37]:
nocs =  pd.read_csv('./complete-pandas-tutorial/data/noc_regions.csv')

In [38]:
nocs.head()

   NOC       region                 notes
0  AFG  Afghanistan                   NaN
1  AHO      Curacao  Netherlands Antilles
2  ALB      Albania                   NaN
3  ALG      Algeria                   NaN
4  AND      Andorra                   NaN

In [42]:
bios = pd.read_csv('complete-pandas-tutorial/data/bios.csv')

In [43]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [60]:
bios = pd.merge(bios, nocs , left_on="born_country", right_on="NOC", how="right")

In [61]:
bios_new = bios[bios["born_country"]=='FRA'][["name","height_cm"]]

In [62]:
bios_new

                        name  height_cm
33712  Jean-François Blanchy        NaN
33713         Arnaud Boetsch      183.0
33714           Jean Borotra      183.0
33715        Jacques Brugnon      168.0
33716      Nicolas Chatelain      181.0
...                      ...        ...
38850          James Clugnet        NaN
38851        Margaux Hackett        NaN
38852         Elliott Baralo        NaN
38853            Elisa Nakab        NaN
38854         André Foussard      166.0

[5143 rows x 2 columns]

In [63]:
bios

,athlete_id,name,born_date,born_city,born_region,born_country,NOC_x,height_cm,weight_kg,died_date,region_x,notes_x,NOC_y,region_y,notes_y,NOC,region,notes
0,57056.0,Mohammad Ebrahimi,1930-04-11,Kabul,Kabul,AFG,Afghanistan,160.0,63.0,2022-05-22,NaN,NaN,AFG,Afghanistan,NaN,AFG,Afghanistan,NaN
1,57062.0,Kayum Ayub,1947-06-21,Kabul,Kabul,AFG,Afghanistan,176.0,78.0,NaN,NaN,NaN,AFG,Afghanistan,NaN,AFG,Afghanistan,NaN
2,57064.0,Aka-Jahan Dastagir,1946-06-05,Kabul,Kabul,AFG,Afghanistan,170.0,70.0,NaN,NaN,NaN,AFG,Afghanistan,NaN,AFG,Afghanistan,NaN
3,57065.0,Ghulam Dastagir,1945-07-24,Kabul,Kabul,AFG,Afghanistan,180.0,87.0,NaN,NaN,NaN,AFG,Afghanistan,NaN,AFG,Afghanistan,NaN
4,57066.0,Ahmad Djan,1948-02-10,Kabul,Kabul,AFG,Afghanistan,165.0,52.0,NaN,NaN,NaN,AFG,Afghanistan,NaN,AFG,Afghanistan,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110661,147637.0,Donata Katai,2004-05-07,Harare,Harare,ZIM,Zimbabwe,NaN,NaN,NaN,NaN,NaN,ZIM,Zimbabwe,NaN,ZIM,Zimbabwe,NaN
110662,147638.0,Ngoni Makusha,1994-06-29,Chitungwiza,Harare,ZIM,Zimbabwe,NaN,NaN,NaN,NaN,NaN,ZIM,Zimbabwe,NaN,ZIM,Zimbabwe,NaN
110663,147639.0,Scott Vincent,1992-05-20,Harare,Harare,ZIM,Zimbabwe,181.0,NaN,NaN,NaN,NaN,ZIM,Zimbabwe,NaN,ZIM,Zimbabwe,NaN
110664,147640.0,Peter Purcell-Gilpin,1994-07-04,Harare,Harare,ZIM,Zimbabwe,189.0,84.0,NaN,NaN,NaN,ZIM,Zimbabwe,NaN,ZIM,Zimbabwe,NaN
110665,147641.0,Peter Wetzlar,1997-02-27,Harare,Harare,ZIM,Zimbabwe,NaN,NaN,NaN,NaN,NaN,ZIM,Zimbabwe,NaN,ZIM,Zimbabwe,NaN

In [70]:
bios.query('born_country=="ZIM" & NOC=="ZIM"')

,athlete_id,name,born_date,born_city,born_region,born_country,NOC_x,height_cm,weight_kg,died_date,region_x,notes_x,NOC_y,region_y,notes_y,NOC,region,notes
110559,2049.0,Robin Sampson,1940-11-23,Bulawayo,Bulawayo,ZIM,New Zealand,183.0,NaN,NaN,NaN,NaN,ZIM,Zimbabwe,NaN,ZIM,Zimbabwe,NaN
110560,2826.0,Byron Black,1969-10-06,Harare,Harare,ZIM,Zimbabwe,175.0,70.0,NaN,NaN,NaN,ZIM,Zimbabwe,NaN,ZIM,Zimbabwe,NaN
110561,2827.0,Wayne Black,1973-11-14,Harare,Harare,ZIM,Zimbabwe,170.0,70.0,NaN,NaN,NaN,ZIM,Zimbabwe,NaN,ZIM,Zimbabwe,NaN
110562,2829.0,Philip Tuckniss,1962-05-05,Harare,Harare,ZIM,Zimbabwe,183.0,70.0,NaN,NaN,NaN,ZIM,Zimbabwe,NaN,ZIM,Zimbabwe,NaN
110563,7879.0,Jannie Gibson,1941-05-15,Bulawayo,Bulawayo,ZIM,Zimbabwe,186.0,48.0,NaN,NaN,NaN,ZIM,Zimbabwe,NaN,ZIM,Zimbabwe,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110661,147637.0,Donata Katai,2004-05-07,Harare,Harare,ZIM,Zimbabwe,NaN,NaN,NaN,NaN,NaN,ZIM,Zimbabwe,NaN,ZIM,Zimbabwe,NaN
110662,147638.0,Ngoni Makusha,1994-06-29,Chitungwiza,Harare,ZIM,Zimbabwe,NaN,NaN,NaN,NaN,NaN,ZIM,Zimbabwe,NaN,ZIM,Zimbabwe,NaN
110663,147639.0,Scott Vincent,1992-05-20,Harare,Harare,ZIM,Zimbabwe,181.0,NaN,NaN,NaN,NaN,ZIM,Zimbabwe,NaN,ZIM,Zimbabwe,NaN
110664,147640.0,Peter Purcell-Gilpin,1994-07-04,Harare,Harare,ZIM,Zimbabwe,189.0,84.0,NaN,NaN,NaN,ZIM,Zimbabwe,NaN,ZIM,Zimbabwe,NaN
110665,147641.0,Peter Wetzlar,1997-02-27,Harare,Harare,ZIM,Zimbabwe,NaN,NaN,NaN,NaN,NaN,ZIM,Zimbabwe,NaN,ZIM,Zimbabwe,NaN

In [ ]:
bios.to_csv('bios.csv',index=False)

In [73]:
actors= pd.read_csv('archive/bollywood-actors.csv',encoding="latin-1")
actresses= pd.read_csv('archive/bollywood-actress.csv',encoding="latin-1")

In [75]:
pd.concat([actors,actresses])

                    Name  Height(in cm)       Debut aslead role  ÿÿ
0    Aaditya Shrivastava            178                     NaN NaN
1             Aamir Khan            163                     NaN NaN
2             Abhay Deol            180                     NaN NaN
3      Abhishek Bachchan            186                     NaN NaN
4        Aditya Pancholi            185                     NaN NaN
..                   ...            ...                     ...  ..
129       Warina Hussain            163               Loveratri NaN
130          Yami Gautam            161             Vicky Donor NaN
131          Zaira Wasim            155                  Dangal NaN
132          Zarine Khan            165                    Veer NaN
133          Zeenat Aman            175  Hare Rama Hare Krishna NaN

[273 rows x 4 columns]